"""analysis batches

Revision ID: d6f82259b67a
Revises: 34af8024d31b
Create Date: 2026-07-16 21:56:07.957970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6f82259b67a'
down_revision: Union[str, None] = '34af8024d31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_batches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vacancy_id', sa.String(length=32), nullable=False),
    sa.Column('provider_batch_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('processing', 'done', 'error', name='batchstatus'), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_batches_provider_batch_id'), ['provider_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_batches_vacancy_id'), ['vacancy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_batches_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_batches_provider_batch_id'))

    op.drop_table('analysis_batches')
    # ### end Alembic commands ###
