"""orgs members plans

Revision ID: eebb04e5a658
Revises: d6f82259b67a
Create Date: 2026-07-16 22:01:02.580521
"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eebb04e5a658'
down_revision: Union[str, None] = 'd6f82259b67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _backfill() -> None:
    """Каждому существующему пользователю — персональное пространство (owner),
    существующие вакансии привязываются к пространству их владельца."""
    bind = op.get_bind()
    users = bind.execute(sa.text("SELECT id, email, name FROM users")).fetchall()
    now = datetime.now(timezone.utc)
    for user_id, email, name in users:
        org_id = uuid.uuid4().hex
        ws_name = ((name or (email or "").split("@")[0]) + " — рабочее пространство")
        bind.execute(
            sa.text(
                "INSERT INTO organizations "
                "(id, name, plan, analyses_used, period_start, created_at) "
                "VALUES (:id, :name, 'free', 0, :now, :now)"
            ),
            {"id": org_id, "name": ws_name, "now": now},
        )
        bind.execute(
            sa.text(
                "INSERT INTO memberships (id, org_id, user_id, role, created_at) "
                "VALUES (:id, :org_id, :user_id, 'owner', :now)"
            ),
            {"id": uuid.uuid4().hex, "org_id": org_id, "user_id": user_id, "now": now},
        )
        bind.execute(
            sa.text("UPDATE users SET active_org_id = :org_id WHERE id = :uid"),
            {"org_id": org_id, "uid": user_id},
        )
        bind.execute(
            sa.text("UPDATE vacancies SET org_id = :org_id WHERE owner_id = :uid"),
            {"org_id": org_id, "uid": user_id},
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plantier'), nullable=False),
    sa.Column('analyses_used', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'recruiter', name='role'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'recruiter', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_org_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(
            'fk_users_active_org', 'organizations', ['active_org_id'], ['id']
        )

    # org_id добавляем как nullable, заполняем backfill'ом, затем делаем NOT NULL
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=32), nullable=True))

    _backfill()

    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.alter_column('org_id', existing_type=sa.String(length=32), nullable=False)
        batch_op.create_index(batch_op.f('ix_vacancies_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_vacancies_org', 'organizations', ['org_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vacancies_org', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vacancies_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_active_org', type_='foreignkey')
        batch_op.drop_column('active_org_id')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_org_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
